import { Booking } from '../types'

export const mockBookings: Booking[] = [
  // 今日のテスト用予約
  {
    id: "today-1",
    owner_id: "1",
    dog_id: "1",
    service_type: "保育園",
    booking_date: new Date().toISOString().split('T')[0], // 今日の日付
    booking_time: "09:00-17:00",
    status: "確定",
    amount: 5000,
    payment_status: "支払い済み",
    memo: "今日の一日預かりコース",
    dog: {
      id: "1",
      name: "ポチ",
      owner_id: "1",
      breed: "柴犬",
      sex: "オス",
      birthdate: "2020-05-15",
      notes: "人懐っこい、活発、特に問題なし、アレルギーなし",
      created_at: "2024-01-15T09:00:00Z",
    },
    owner: {
      id: "1",
      name: "山田太郎",
      email: "yamada@example.com",
      phone: "090-1234-5678",
      created_at: "2024-01-15T09:00:00Z",
    }
  },
  // 明日の予約
  {
    id: "tomorrow-1",
    owner_id: "0", // user@example.comのowner_id
    dog_id: "user-dog-1",
    service_type: "保育園",
    booking_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 明日の日付
    booking_time: "09:00-17:00",
    status: "確定",
    amount: 5000,
    payment_status: "支払い済み",
    memo: "明日の一日預かりコース",
    dog: {
      id: "user-dog-1",
      name: "タロウ",
      owner_id: "0",
      breed: "柴犬",
      sex: "オス",
      birthdate: "2020-03-10",
      notes: "元気で活発",
      created_at: "2024-01-10T09:00:00Z",
    },
    owner: {
      id: "0",
      name: "テストユーザー",
      email: "user@example.com",
      phone: "090-0000-0000",
      created_at: "2024-01-10T09:00:00Z",
    }
  },
  // 来週の予約
  {
    id: "next-week-1",
    owner_id: "0", // user@example.comのowner_id
    dog_id: "user-dog-1",
    service_type: "保育園",
    booking_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 来週の日付
    booking_time: "10:00-16:00",
    status: "確定",
    amount: 4500,
    payment_status: "支払い済み",
    memo: "来週の預かりコース",
    dog: {
      id: "user-dog-1",
      name: "タロウ",
      owner_id: "0",
      breed: "柴犬",
      sex: "オス",
      birthdate: "2020-03-10",
      notes: "元気で活発",
      created_at: "2024-01-10T09:00:00Z",
    },
    owner: {
      id: "0",
      name: "テストユーザー",
      email: "user@example.com",
      phone: "090-0000-0000",
      created_at: "2024-01-10T09:00:00Z",
    }
  },
  {
    id: "1",
    owner_id: "1",
    dog_id: "1",
    booking_date: "2024-12-25",
    booking_time: "09:00",
    service_type: "保育園",
    amount: 3500,
    status: "確定",
    memo: "午前中にお迎えお願いします",
    payment_status: "支払い済み",
  },
  {
    id: "2",
    owner_id: "2",
    dog_id: "2",
    booking_date: "2024-12-26",
    booking_time: "10:00",
    service_type: "保育園",
    amount: 3500,
    status: "確定",
    memo: "アレルギーがあるため、特別なフードをお持ちします",
    payment_status: "支払い済み",
  },
  {
    id: "3",
    owner_id: "3",
    dog_id: "3",
    booking_date: "2024-12-27",
    booking_time: "08:30",
    service_type: "保育園",
    amount: 3500,
    status: "確定",
    memo: "お散歩多めでお願いします",
    payment_status: "支払い済み",
  },
  {
    id: "4",
    owner_id: "1",
    dog_id: "4",
    booking_date: "2024-12-28",
    booking_time: "11:00",
    service_type: "体験",
    amount: 2000,
    status: "受付中",
    memo: "初回体験です",
    payment_status: "未払い",
  },
  {
    id: "5",
    owner_id: "2",
    dog_id: "2",
    booking_date: "2024-12-24",
    booking_time: "14:00",
    service_type: "保育園",
    amount: 3500,
    status: "完了",
    memo: "お疲れ様でした",
    payment_status: "支払い済み",
  },
  {
    id: "6",
    owner_id: "3",
    dog_id: "3",
    booking_date: "2024-12-29",
    booking_time: "09:30",
    service_type: "イベント",
    amount: 3000,
    status: "確定",
    memo: "クリスマスイベント参加",
    payment_status: "支払い済み",
  },
  {
    id: "7",
    owner_id: "4",
    dog_id: "5",
    booking_date: "2024-12-30",
    booking_time: "13:00",
    service_type: "保育園",
    amount: 3500,
    status: "受付中",
    memo: "年末最後の預かり",
    payment_status: "未払い",
  },
]
