import { Dog } from '../types'

export const mockDogs: Dog[] = [
  {
    id: "1",
    owner_id: "1",
    name: "ポチ",
    breed: "ゴールデンレトリバー",
    sex: "オス",
    birthdate: "2021-01-15",
    avatar: "/placeholder.svg?height=40&width=40",
    notes: "とても人懐っこい性格です",
  },
  {
    id: "2",
    owner_id: "2",
    name: "ハナ",
    breed: "柴犬",
    sex: "メス",
    birthdate: "2022-03-20",
    avatar: "/placeholder.svg?height=40&width=40",
    notes: "元気いっぱいで遊び好きです",
  },
  {
    id: "3",
    owner_id: "3",
    name: "チョコ",
    breed: "トイプードル",
    sex: "オス",
    birthdate: "2023-05-10",
    avatar: "/placeholder.svg?height=40&width=40",
    notes: "少し臆病ですが、慣れると甘えん坊です",
  },
  {
    id: "4",
    owner_id: "1",
    name: "ルイ",
    breed: "トイプードル",
    sex: "オス",
    birthdate: "2022-08-15",
    avatar: "/placeholder.svg?height=40&width=40",
    notes: "活発で社交的な性格",
  },
  {
    id: "5",
    owner_id: "2",
    name: "ココ",
    breed: "チワワ",
    sex: "メス",
    birthdate: "2021-12-03",
    avatar: "/placeholder.svg?height=40&width=40",
    notes: "小さいけれど勇敢です",
  },
  {
    id: "6",
    owner_id: "4",
    name: "マロン",
    breed: "ダックスフンド",
    sex: "オス",
    birthdate: "2020-06-18",
    avatar: "/placeholder.svg?height=40&width=40",
    notes: "のんびりした性格で癒し系",
  },
  {
    id: "7",
    owner_id: "5",
    name: "サクラ",
    breed: "ポメラニアン",
    sex: "メス",
    birthdate: "2023-02-14",
    avatar: "/placeholder.svg?height=40&width=40",
    notes: "美しい毛色で人気者",
  },
]
