import { Event } from "../types"

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "犬の健康セミナー",
    description: "獣医師による犬の健康管理についての講座",
    date: "2025年9月15日",
    startTime: "14:00",
    endTime: "16:00",
    location: "今治市総合体育館",
    organizer: "ImabariOne",
    category: "health",
    price: "無料",
    status: "published",
    image: "/photo/img_salon_001.jpg",
    details: "愛犬の健康を保つための基本的な知識や、日常のケア方法について学べます。獣医師による質疑応答の時間も設けています。",
    benefits: ["健康チェックシート", "獣医師への質問時間", "愛犬の写真撮影会"],
    createdAt: "2025-08-20T10:00:00Z",
    updatedAt: "2025-08-20T10:00:00Z"
  },
  {
    id: "2", 
    title: "ドッグランイベント",
    description: "愛犬と一緒に楽しめるドッグランでの交流会",
    date: "2025年9月22日",
    startTime: "10:00",
    endTime: "12:00",
    location: "ASICS SATOYAMA STADIUM",
    organizer: "今治市",
    category: "sports",
    price: 1000,
    status: "published",
    image: "/photo/header_dogrun2.jpg",
    details: "広いドッグランで愛犬と自由に遊んでいただけます。他の飼い主さんとの交流や情報交換もお楽しみください。",
    benefits: ["ドッグラン利用料込み", "飲み物サービス", "記念品プレゼント"],
    createdAt: "2025-08-20T10:00:00Z",
    updatedAt: "2025-08-20T10:00:00Z"
  },
  {
    id: "3",
    title: "愛犬写真撮影会",
    description: "プロカメラマンによる愛犬の写真撮影",
    date: "2025年9月29日", 
    startTime: "13:00",
    endTime: "17:00",
    location: "今治城公園",
    organizer: "フォトスタジオ今治",
    category: "outdoor",
    price: 3000,
    status: "published",
    image: "/photo/PXL_20250706_002732082.PORTRAIT.jpg",
    details: "美しい今治城を背景に、プロカメラマンが愛犬の魅力を最大限に引き出した写真を撮影します。撮影データはすべてお渡しします。",
    benefits: ["撮影データ30枚以上", "プリント写真5枚", "オリジナルフォトフレーム"],
    createdAt: "2025-08-20T10:00:00Z",
    updatedAt: "2025-08-20T10:00:00Z"
  },
  {
    id: "4",
    title: "犬のしつけ教室",
    description: "基本的なしつけから応用まで学べる教室",
    date: "2025年10月6日",
    startTime: "09:00", 
    endTime: "11:00",
    location: "ImabariOne 研修室",
    organizer: "ドッグトレーナー協会",
    category: "education",
    price: 2500,
    status: "published",
    image: "/photo/fc1.jpg",
    details: "お座り、待て、来いなどの基本コマンドから、散歩のマナーまで、実践的なしつけ方法を学べます。",
    benefits: ["しつけガイドブック", "個別アドバイス", "フォローアップ相談"],
    createdAt: "2025-08-20T10:00:00Z",
    updatedAt: "2025-08-20T10:00:Z"
  }
]
