"""phase3 walk_reports

Revision ID: 02e2193e872d
Revises: 6ac0363adf65
Create Date: 2025-08-25 23:18:42.963210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e2193e872d'
down_revision = '6ac0363adf65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('walk_event_id', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('photos_json', sa.Text(), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLIC', 'PRIVATE', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['walk_event_id'], ['walk_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_walk_reports_author_user_id', 'walk_reports', ['author_user_id'], unique=False)
    op.create_index('ix_walk_reports_created_at', 'walk_reports', ['created_at'], unique=False)
    op.create_index('ix_walk_reports_status', 'walk_reports', ['status'], unique=False)
    op.create_index('ix_walk_reports_walk_event_id', 'walk_reports', ['walk_event_id'], unique=False)
    op.drop_index(op.f('ix_health_records_author_user_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_dog_date'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_dog_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_record_date'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_index(op.f('ix_meals_dog_fed_at'), table_name='meals')
    op.drop_index(op.f('ix_meals_dog_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_fed_at'), table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('dog_id', sa.VARCHAR(), nullable=False),
    sa.Column('fed_at', sa.DATETIME(), nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=8), nullable=True),
    sa.Column('amount_g', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('brand', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_fed_at'), 'meals', ['fed_at'], unique=False)
    op.create_index(op.f('ix_meals_dog_id'), 'meals', ['dog_id'], unique=False)
    op.create_index(op.f('ix_meals_dog_fed_at'), 'meals', ['dog_id', 'fed_at'], unique=False)
    op.create_table('health_records',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('dog_id', sa.VARCHAR(), nullable=False),
    sa.Column('record_date', sa.DATE(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('health_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('symptoms', sa.TEXT(), nullable=True),
    sa.Column('treatment', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('vet_visit', sa.VARCHAR(length=255), nullable=True),
    sa.Column('author_user_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_records_record_date'), 'health_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_health_records_dog_id'), 'health_records', ['dog_id'], unique=False)
    op.create_index(op.f('ix_health_records_dog_date'), 'health_records', ['dog_id', 'record_date'], unique=False)
    op.create_index(op.f('ix_health_records_author_user_id'), 'health_records', ['author_user_id'], unique=False)
    op.drop_index('ix_walk_reports_walk_event_id', table_name='walk_reports')
    op.drop_index('ix_walk_reports_status', table_name='walk_reports')
    op.drop_index('ix_walk_reports_created_at', table_name='walk_reports')
    op.drop_index('ix_walk_reports_author_user_id', table_name='walk_reports')
    op.drop_table('walk_reports')
    # ### end Alembic commands ###