"""phase2 diary_entries

Revision ID: 0f3a53e6a1a4
Revises: 193b168e4ae6
Create Date: 2025-08-25 20:42:50.801858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3a53e6a1a4'
down_revision = '193b168e4ae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photos_json', sa.Text(), nullable=True),
    sa.Column('mood', sa.Enum('HAPPY', 'NORMAL', 'TIRED', 'SICK', name='mood'), nullable=True),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diary_entries_author_user_id', 'diary_entries', ['author_user_id'], unique=False)
    op.create_index('ix_diary_entries_dog_date', 'diary_entries', ['dog_id', 'entry_date'], unique=False)
    op.create_index('ix_diary_entries_dog_id', 'diary_entries', ['dog_id'], unique=False)
    op.create_index('ix_diary_entries_entry_date', 'diary_entries', ['entry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diary_entries_entry_date', table_name='diary_entries')
    op.drop_index('ix_diary_entries_dog_id', table_name='diary_entries')
    op.drop_index('ix_diary_entries_dog_date', table_name='diary_entries')
    op.drop_index('ix_diary_entries_author_user_id', table_name='diary_entries')
    op.drop_table('diary_entries')
    # ### end Alembic commands ###