"""phase2 bookings

Revision ID: 193b168e4ae6
Revises: 0a85ba932d0f
Create Date: 2025-08-25 18:50:36.650719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193b168e4ae6'
down_revision = '0a85ba932d0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('service_type', sa.Enum('TRIAL', 'DAYCARE', 'EVENT', 'OTHER', name='servicetype'), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_booking_date', 'bookings', ['booking_date'], unique=False)
    op.create_index('ix_bookings_dog_date_time', 'bookings', ['dog_id', 'booking_date', 'booking_time'], unique=False)
    op.create_index('ix_bookings_dog_id', 'bookings', ['dog_id'], unique=False)
    op.create_index('ix_bookings_owner_id', 'bookings', ['owner_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_owner_id', table_name='bookings')
    op.drop_index('ix_bookings_dog_id', table_name='bookings')
    op.drop_index('ix_bookings_dog_date_time', table_name='bookings')
    op.drop_index('ix_bookings_booking_date', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###