"""phase2 meals

Revision ID: 6582c353240e
Revises: 876a1557f28d
Create Date: 2025-08-25 22:22:03.363312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6582c353240e'
down_revision = '876a1557f28d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('fed_at', sa.DateTime(), nullable=False),
    sa.Column('meal_type', sa.Enum('DRY', 'WET', 'HANDMADE', 'SNACK', name='mealtype'), nullable=True),
    sa.Column('amount_g', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meals_dog_fed_at', 'meals', ['dog_id', 'fed_at'], unique=False)
    op.create_index('ix_meals_dog_id', 'meals', ['dog_id'], unique=False)
    op.create_index('ix_meals_fed_at', 'meals', ['fed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meals_fed_at', table_name='meals')
    op.drop_index('ix_meals_dog_id', table_name='meals')
    op.drop_index('ix_meals_dog_fed_at', table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###