"""add walk_participants table

Revision ID: 6ac0363adf65
Revises: e8df0ad412fe
Create Date: 2025-08-25 22:59:53.323348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac0363adf65'
down_revision = 'e8df0ad412fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'APPROVED', 'REJECTED', 'CANCELLED', name='participantstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['walk_events.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'owner_id', 'dog_id', name='uq_event_owner_dog')
    )
    op.create_index('ix_walk_participants_event_id', 'walk_participants', ['event_id'], unique=False)
    op.create_index('ix_walk_participants_owner_id', 'walk_participants', ['owner_id'], unique=False)
    op.create_index('ix_walk_participants_status', 'walk_participants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_walk_participants_status', table_name='walk_participants')
    op.drop_index('ix_walk_participants_owner_id', table_name='walk_participants')
    op.drop_index('ix_walk_participants_event_id', table_name='walk_participants')
    op.drop_table('walk_participants')
    # ### end Alembic commands ###