"""phase2 health_records

Revision ID: 876a1557f28d
Revises: 0f3a53e6a1a4
Create Date: 2025-08-25 21:45:52.544012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876a1557f28d'
down_revision = '0f3a53e6a1a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('health_status', sa.Enum('EXCELLENT', 'GOOD', 'NORMAL', 'POOR', 'CRITICAL', name='healthstatus'), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('vet_visit', sa.String(length=255), nullable=True),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_records_author_user_id', 'health_records', ['author_user_id'], unique=False)
    op.create_index('ix_health_records_dog_date', 'health_records', ['dog_id', 'record_date'], unique=False)
    op.create_index('ix_health_records_dog_id', 'health_records', ['dog_id'], unique=False)
    op.create_index('ix_health_records_record_date', 'health_records', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_records_record_date', table_name='health_records')
    op.drop_index('ix_health_records_dog_id', table_name='health_records')
    op.drop_index('ix_health_records_dog_date', table_name='health_records')
    op.drop_index('ix_health_records_author_user_id', table_name='health_records')
    op.drop_table('health_records')
    # ### end Alembic commands ###