"""add dog_evaluations table

Revision ID: b758e7932be9
Revises: 02e2193e872d
Create Date: 2025-08-25 23:39:09.359617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b758e7932be9'
down_revision = '02e2193e872d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dog_id', sa.String(), nullable=False),
    sa.Column('evaluated_on', sa.Date(), nullable=False),
    sa.Column('ears', sa.Enum('OK', 'SLIGHTLY_DISLIKES', 'CLEARLY_DISLIKES', name='bodypartassessment'), nullable=True),
    sa.Column('muzzle', sa.Enum('OK', 'SLIGHTLY_DISLIKES', 'CLEARLY_DISLIKES', name='bodypartassessment'), nullable=True),
    sa.Column('neck', sa.Enum('OK', 'SLIGHTLY_DISLIKES', 'CLEARLY_DISLIKES', name='bodypartassessment'), nullable=True),
    sa.Column('back', sa.Enum('OK', 'SLIGHTLY_DISLIKES', 'CLEARLY_DISLIKES', name='bodypartassessment'), nullable=True),
    sa.Column('paws', sa.Enum('OK', 'SLIGHTLY_DISLIKES', 'CLEARLY_DISLIKES', name='bodypartassessment'), nullable=True),
    sa.Column('tail', sa.Enum('OK', 'SLIGHTLY_DISLIKES', 'CLEARLY_DISLIKES', name='bodypartassessment'), nullable=True),
    sa.Column('human_affinity_score', sa.Integer(), nullable=True),
    sa.Column('dog_affinity_score', sa.Integer(), nullable=True),
    sa.Column('noise_tolerance_score', sa.Integer(), nullable=True),
    sa.Column('crate_tolerance_score', sa.Integer(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('evaluator_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['evaluator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dog_evaluations_dog_id', 'dog_evaluations', ['dog_id'], unique=False)
    op.create_index('ix_dog_evaluations_evaluated_on', 'dog_evaluations', ['evaluated_on'], unique=False)
    op.create_index('ix_dog_evaluations_evaluator_user_id', 'dog_evaluations', ['evaluator_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dog_evaluations_evaluator_user_id', table_name='dog_evaluations')
    op.drop_index('ix_dog_evaluations_evaluated_on', table_name='dog_evaluations')
    op.drop_index('ix_dog_evaluations_dog_id', table_name='dog_evaluations')
    op.drop_table('dog_evaluations')
    # ### end Alembic commands ###