"""phase3 walk_events

Revision ID: e8df0ad412fe
Revises: 6582c353240e
Create Date: 2025-08-25 22:39:36.956815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8df0ad412fe'
down_revision = '6582c353240e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECRUITING', 'FULL', 'FINISHED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('meeting_point', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_walk_events_created_by', 'walk_events', ['created_by_user_id'], unique=False)
    op.create_index('ix_walk_events_event_date', 'walk_events', ['event_date'], unique=False)
    op.create_index('ix_walk_events_status', 'walk_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_walk_events_status', table_name='walk_events')
    op.drop_index('ix_walk_events_event_date', table_name='walk_events')
    op.drop_index('ix_walk_events_created_by', table_name='walk_events')
    op.drop_table('walk_events')
    # ### end Alembic commands ###