"""priority_d comments

Revision ID: f5bf7156a523
Revises: 8824301f4867
Create Date: 2025-08-26 05:20:30.299272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bf7156a523'
down_revision = '8824301f4867'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_author_user_id', 'comments', ['author_user_id'], unique=False)
    op.create_index('ix_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_comments_post_id', 'comments', ['post_id'], unique=False)
    op.alter_column('bookings', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bookings', 'service_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('体験', '保育園', 'イベント', 'その他', name='servicetype'),
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('受付中', '確定', '完了', '取消', name='bookingstatus'),
               existing_nullable=False)
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('未払い', '支払い済み', '返金済み', name='paymentstatus'),
               existing_nullable=False)
    op.alter_column('diary_entries', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('diary_entries', 'mood',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('うれしい', 'ふつう', 'つかれた', '体調不良', name='mood'),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dog_evaluations', 'ears',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'muzzle',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'neck',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'back',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'paws',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'tail',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               existing_nullable=True)
    op.drop_index(op.f('ix_dogs_name'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_owner_id'), table_name='dogs')
    op.add_column('health_records', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('health_records', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('health_records', sa.Column('health_status', sa.Enum('EXCELLENT', 'GOOD', 'NORMAL', 'POOR', 'CRITICAL', name='healthstatus'), nullable=True))
    op.add_column('health_records', sa.Column('symptoms', sa.Text(), nullable=True))
    op.add_column('health_records', sa.Column('treatment', sa.Text(), nullable=True))
    op.add_column('health_records', sa.Column('vet_visit', sa.String(length=255), nullable=True))
    op.add_column('health_records', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('health_records', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('health_records', 'author_user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('health_records', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.create_index('ix_health_records_author_user_id', 'health_records', ['author_user_id'], unique=False)
    op.create_index('ix_health_records_dog_date', 'health_records', ['dog_id', 'record_date'], unique=False)
    op.drop_constraint(None, 'health_records', type_='foreignkey')
    op.create_foreign_key(None, 'health_records', 'dogs', ['dog_id'], ['id'])
    op.drop_column('health_records', 'temperature_c')
    op.drop_column('health_records', 'weight_kg')
    op.alter_column('meals', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('meals', 'meal_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ドライ', 'ウェット', '手作り', 'おやつ', name='mealtype'),
               existing_nullable=True)
    op.alter_column('meals', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('meals', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.create_foreign_key(None, 'meals', 'dogs', ['dog_id'], ['id'])
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_index(op.f('ix_owners_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_user_id'), table_name='owners')
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('有効', '無効', '停止', name='userstatus'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('利用者', '管理者', 'スーパー管理者', name='userrole'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('walk_events', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('walk_events', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('単独', 'グループ', 'スポンサー付', '大会', name='eventtype'),
               existing_nullable=False)
    op.alter_column('walk_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('予定', '締切', '中止', name='eventstatus'),
               existing_nullable=False)
    op.alter_column('walk_participants', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('walk_participants', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('予約', '参加', '不参加', '取消', name='participantstatus'),
               existing_nullable=False)
    op.alter_column('walk_participants', 'fee_paid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('walk_participants', 'refunded',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint('uq_walk_event_owner_dog', 'walk_participants', ['walk_event_id', 'owner_id', 'dog_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_walk_event_owner_dog', 'walk_participants', type_='unique')
    op.alter_column('walk_participants', 'refunded',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('walk_participants', 'fee_paid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('walk_participants', 'status',
               existing_type=sa.Enum('予約', '参加', '不参加', '取消', name='participantstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('walk_participants', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('walk_events', 'status',
               existing_type=sa.Enum('予定', '締切', '中止', name='eventstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('walk_events', 'type',
               existing_type=sa.Enum('単独', 'グループ', 'スポンサー付', '大会', name='eventtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('walk_events', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('利用者', '管理者', 'スーパー管理者', name='userrole'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.Enum('有効', '無効', '停止', name='userstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_owners_user_id'), 'owners', ['user_id'], unique=False)
    op.create_index(op.f('ix_owners_name'), 'owners', ['name'], unique=False)
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=False)
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.create_foreign_key(None, 'meals', 'dogs', ['dog_id'], ['id'], ondelete='CASCADE')
    op.alter_column('meals', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('meals', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('meals', 'meal_type',
               existing_type=sa.Enum('ドライ', 'ウェット', '手作り', 'おやつ', name='mealtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('meals', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('health_records', sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('health_records', sa.Column('temperature_c', sa.DECIMAL(precision=4, scale=1), nullable=True))
    op.drop_constraint(None, 'health_records', type_='foreignkey')
    op.create_foreign_key(None, 'health_records', 'dogs', ['dog_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_health_records_dog_date', table_name='health_records')
    op.drop_index('ix_health_records_author_user_id', table_name='health_records')
    op.alter_column('health_records', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('health_records', 'author_user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('health_records', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('health_records', 'updated_at')
    op.drop_column('health_records', 'vet_visit')
    op.drop_column('health_records', 'treatment')
    op.drop_column('health_records', 'symptoms')
    op.drop_column('health_records', 'health_status')
    op.drop_column('health_records', 'temperature')
    op.drop_column('health_records', 'weight')
    op.create_index(op.f('ix_dogs_owner_id'), 'dogs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_dogs_name'), 'dogs', ['name'], unique=False)
    op.alter_column('dog_evaluations', 'tail',
               existing_type=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'paws',
               existing_type=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'back',
               existing_type=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'neck',
               existing_type=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'muzzle',
               existing_type=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'ears',
               existing_type=sa.Enum('OK', '少し嫌がる', '明確に嫌がる', name='bodypartassessment'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
    op.alter_column('dog_evaluations', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('diary_entries', 'mood',
               existing_type=sa.Enum('うれしい', 'ふつう', 'つかれた', '体調不良', name='mood'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('diary_entries', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.Enum('未払い', '支払い済み', '返金済み', name='paymentstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('受付中', '確定', '完了', '取消', name='bookingstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('bookings', 'service_type',
               existing_type=sa.Enum('体験', '保育園', 'イベント', 'その他', name='servicetype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('bookings', 'id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_comments_post_id', table_name='comments')
    op.drop_index('ix_comments_parent_comment_id', table_name='comments')
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_index('ix_comments_author_user_id', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###